### ISSUE TITLE
Include themer-jetbrains in themer packages?

### ISSUE THREAD

**Issue by mjswensen** [tomselvi/themer-jetbrains#1]
Hi @tomselvi , great work on this template!! 🙌 

Do you mind if I:

1. include a link to this repository in the main themer readme, and
2. include `themer-jetbrains` in [themer's GUI](https://github.com/mjswensen/themer-gui)?

Again, excellent work on putting this together—thank you!

**Comment by tamzinselvi** [comment]
Hi @mjswensen,

Thanks!  I'd be honored if you would like to feature this repo on the themer GUI & readme.  It might also be worth taking a look at https://github.com/tomselvi/themer-tmux.

I appreciate your hard work putting this project together, excited to see where this evolves and to continue contributing to the ecosystem.

**Comment by mjswensen** [comment]
Fantastic!

Wow, I am trying out `themer-tmux` on my own tmux setup right now and these themes are wonderful! I will add both `themer-jetbrains` and `themer-tmux` to the GUI and the readme. Thank you again for these great packages!
